### PR TITLE
Port over UX Designer role from next.fusion.net

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@lisaej

**Comment by danielbachhuber** [comment]
@lisaej #reviewmerge

**Comment by lisaej** [comment]
There is actually no mention of UX type of work. I would add in something about:

Assess the usability of the product by defining success metrics, validating and measuring user success.
Know: User research (interviews, focus group), user modeling (personas, scenarios, use cases, user flow), user testing, information architecture, interaction design principles.

**Comment by danielbachhuber** [comment]
> I would add in something about:

Can you make the edits?

**Comment by lisaej** [comment]
Done!

**Pull request merged**
