### PR TITLE
Stub a document about deploying Github to S3

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@antiboredom #reviewmerge?

@noppanit Can you give this a read too for clarity?

**Comment by noppanit** [comment]
Should we include an example of our `.travis.yml` as well?

```
deploy:
  provider: s3
  access_key_id:
    secure: Ex70PI/w0UELGNKFIgmcYWfPg8oY1WQPh7FWH8USN8f0+NG6+SuRgesdXqjD+REnxftpcHGH85Kp+KKotSrTdp6+Y0lL0EyDVof8WBZK++vdnuWDpFdjgO6vmjDW+tia4oUTAO1eDQY2bJRoyrGMxA+a5sw+uA5HdSjF6OI6P80=
  secret_access_key:
    secure: VCQl7zXgTzv1POKOS+LgdwRbijdxaayEPr+1ZDMumCUoEa5iHWwpuMcxwuZNbW2DqEn7jK5JiQuXist4DiwwPDcr31FWAd7lzxgk4L0Z/7ArXqZZy+Wbt9L1eLtwFVNXBNW2EV0QlopKPjBnSMxC7WMUaN7vn4KufZT7YPaqBbc=
  bucket: styleguide.fusion.net
  skip_cleanup: true
  region: us-west-2
  endpoint: styleguide.fusion.net.s3-website-us-west-2.amazonaws.com
  local_dir: styleguide/docs
  on:
    branch: master
```

I think it's worth mentioning that `skip_cleanup: true` is really important otherwise the content might be deleted or cleaned up before it's being deployed to S3.

**Comment by antiboredom** [comment]
@noppanit agreed!

otherwise looks great.

**Comment by danielbachhuber** [comment]
> Should we include an example of our .travis.yml as well?

Not in a public repo. Easy enough to copy out of a private repo.

**Pull request merged**
