### PR TITLE
Add link to application form

### PR DESCRIPTION
**Pull request by davisshaver**
Fixes https://github.com/fusioneng/tech-docs/issues/47

### CODE REVIEW

**Comment by davisshaver** [comment]
@danielbachhuber here's [the template on Google Drive](https://docs.google.com/a/fusion.net/forms/d/1OAb8FebRcfqCRBHx3CYY1kxibJFw9VORHhV14KLadeI/edit) and [live form](https://docs.google.com/forms/d/1OAb8FebRcfqCRBHx3CYY1kxibJFw9VORHhV14KLadeI/viewform). Maybe we should hold hiring chat in-person Friday and discuss?

**Comment by danielbachhuber** [comment]
@davisshaver Given that we're mostly assigning projects right now, do you think transitioning to an application process is necessary? If so, what do you think is the value?

**Comment by davisshaver** [comment]
@daniel if you have changed your mind about this process, fine, but I feel this PR is scoped to "what should the form entail" as we already merged the PR describing the process.

**Comment by danielbachhuber** [comment]
> if you have changed your mind about this process

But the process hasn't included application forms before? Not sure what benefit having an application form provides, when it has the cost of adding more work.

**Comment by pbearne** [comment]
Hi Guys

I hooked into these docs early on and end up at https://careers-fusion.icims.com/jobs/1364/senior-software-engineer/ just checking that I ended up at the right location. As I am getting the feeling that it's not.  So BIG apply here link may be needed :-)

**Comment by davisshaver** [comment]
@pbearne :wave:. Good point. We should have instructions on how to begin the conversation process.

@danielbachhuber The benefit to the pre-app form to pitch the trial is that it makes people think intentionally: Do I want to do a trial? What trial do I want to do? Right now, we are pitching people on a trial project, and I think we'd reduce the number of stalled trials if we add this deliberate action to the step.

**Comment by pbearne** [comment]
And be clear about location / timezone and how you employ is by payroll worldwide or contract outside US. Is it in US dollars or local

**Comment by than** [comment]
Jobs page could also use some boilerplate benefits information.

**Pull request merged**
