### PR TITLE
Draft best practices document for releasing code

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@davisshaver @goldenapples would love your feedback on this

**Comment by goldenapples** [comment]
Do you think its worthwhile to add a step to the release process for WordPress plugins:

* If you are not already watching the plugin, subscribe to the wp.org support forums posts for this plugin. Visit the plugin's support page at `https://wordpress.org/support/plugin/{plugin-slug}`, and there are RSS and email subscription links.

**Comment by danielbachhuber** [comment]
> Do you think its worthwhile to add a step to the release process for WordPress plugins:

Yep, great suggestion. I'll add it after @davisshaver gives it a read.

**Comment by davisshaver** [comment]
Couple questions.

- "Update screenshots" isn't self explanatory. Do we have a link to describe the SVN directory structure? Or do we need to document this here?
- "Update documentation" is also a little vague. As are the changelog and grunt details. Perhaps we should acknowledge missing detail for now, and make a starter plugin kit? Or maybe the WP CLI scaffold covers this structure and we can just point users to that tool.

**Comment by davisshaver** [comment]
I'd like to hold merge of this PR until after shipping Shortcake Bakery. https://trello.com/c/4lbjNSeG/1-shortcake-bakery-v0-1-0

**Comment by danielbachhuber** [comment]
> I'd like to hold merge of this PR until after shipping Shortcake Bakery.

Sounds good. For now, I've created #116 with some changes that will directly merge into this branch.

> Do we have a link to describe the SVN directory structure?

Directory structure isn't relevant — only naming conventions.

> "Update documentation" is also a little vague.

What would you clarify?

>  As are the changelog and grunt details. 

These are mentioned in the WordPress section?

> Perhaps we should acknowledge missing detail for now, and make a starter plugin kit?

I think both. Seems like starter plugin kit is pretty ripe.

**Pull request merged**
