### PR TITLE
Within Vagrant, need to specify bash for running .sh

### PR DESCRIPTION
**Pull request by davisshaver**

### CODE REVIEW

**Comment by davisshaver** [comment]
@goldenapples Review/merge?

**Comment by goldenapples** [comment]
That shouldn't be necessary, should it? 

Bash is already specified in the shebang line: https://github.com/fusioneng/fusion-theme/blob/master/bin/install-wp-tests.sh#L1

**Comment by davisshaver** [comment]
@goldenapples Here's what I saw as output...

```
vagrant@vip:/srv/www/wp-content/themes/vip/fusion-theme$ bin/install-wp-tests.sh wordpress_test root ''
-bash: bin/install-wp-tests.sh: Permission denied
vagrant@vip:/srv/www/wp-content/themes/vip/fusion-theme$ sudo bin/install-wp-tests.sh wordpress_test root ''
sudo: bin/install-wp-tests.sh: command not found
vagrant@vip:/srv/www/wp-content/themes/vip/fusion-theme$ ls -a
.                        composer.json         .gitignore    page-newsletter-confirmation.php  search.php                    single-fusion_video.php
..                       composer.lock         .gitmodules   page-newsletter-subscribe.php     sidebar-archive.php           single.php
404.php                  .editorconfig         Gruntfile.js  page.php                          sidebar-author.php            style.css
archive-fusion_show.php  embed.php             header.php    page-tve-authenticator.php        sidebar-authors.php           styleguide
archive.php              embed-riseup-300.php  home.php      parts                             single-fusion_comic.php       taxonomy-fusion_section-project-earth.php
assets                   footer.php            inc           php-tests                         single-fusion_gallery.php     taxonomy.php
author.php               functions.php         index.php     phpunit.xml                       single-fusion_liveblog.php    .travis.yml
authors.php              Gemfile               js-tests      README.md                         single-fusion_newsletter.php  vendor
bin                      Gemfile.lock          lib           schedule.php                      single-fusion_show.php        wp-cli.yml
comments.php             .git                  package.json  .scss-lint.yml                    single-fusion_sponsored.php   wpcom-meta.php
vagrant@vip:/srv/www/wp-content/themes/vip/fusion-theme$ bin/install-wp-tests.sh wordpress_test root ''
-bash: bin/install-wp-tests.sh: Permission denied
vagrant@vip:/srv/www/wp-content/themes/vip/fusion-theme$ bash bin/install-wp-tests.sh wordpress_test root ''
+ install_wp
+ '[' -d /tmp/wordpress/ ']'
+ mkdir -p /tmp/wordpress/
+ '[' latest == latest ']'
+ local ARCHIVE_NAME=latest
+ wget -nv -O /tmp/wordpress.tar.gz http://wordpress.org/latest.tar.gz
2015-06-15 13:49:56 URL:https://wordpress.org/latest.tar.gz [6307937/6307937] -> "/tmp/wordpress.tar.gz" [1]
+ tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C /tmp/wordpress/
+ wget -nv -O /tmp/wordpress//wp-content/db.php https://raw.github.com/markoheijnen/wp-mysqli/master/db.php
2015-06-15 13:49:57 URL:https://raw.githubusercontent.com/markoheijnen/wp-mysqli/master/db.php [87/87] -> "/tmp/wordpress//wp-content/db.php" [1]
+ checkout_vip
+ PLUGINS_DIR=/tmp/wordpress//wp-content/themes/vip/plugins
+ PLUGINS_FILE=vip-plugins.tar.gz
+ PLUGINS_URL=http://wp.fusion.net/builds/vip-plugins.tar.gz
+ '[' -d /tmp/wordpress//wp-content/themes/vip/plugins ']'
+ mkdir -p /tmp/wordpress//wp-content/themes/vip/plugins
++ grep 'HTTP/1.1 200 OK'
++ wget -S --spider http://wp.fusion.net/builds/vip-plugins.tar.gz
+ [[ -n   HTTP/1.1 200 OK ]]
+ wget -nv -O /tmp/vip-plugins.tar.gz http://wp.fusion.net/builds/vip-plugins.tar.gz
2015-06-15 13:50:03 URL:http://wp.fusion.net/builds/vip-plugins.tar.gz [26168884/26168884] -> "/tmp/vip-plugins.tar.gz" [1]
+ tar --strip-components=1 -zxmf /tmp/vip-plugins.tar.gz -C /tmp/wordpress//wp-content/themes/vip/plugins
+ install_test_suite
++ uname -s
+ [[ Linux == \D\a\r\w\i\n ]]
+ local ioption=-i
+ PHPUNIT_FILE=phpunit-includes.tar.gz
+ PHPUNIT_URL=http://wp.fusion.net/builds/phpunit-includes.tar.gz
+ '[' '!' -d /srv/www/wp-tests/tests/phpunit/ ']'
+ cd /srv/www/wp-tests/tests/phpunit/
+ '[' '!' -f wp-tests-config.php ']'
+ wget -nv -O wp-tests-config.php http://develop.svn.wordpress.org/trunk/wp-tests-config-sample.php
2015-06-15 13:50:05 URL:http://develop.svn.wordpress.org/trunk/wp-tests-config-sample.php [1374/1374] -> "wp-tests-config.php" [1]
+ sed -i 's:dirname( __FILE__ ) . '\''/src/'\'':'\''/tmp/wordpress/'\'':' wp-tests-config.php
+ sed -i s/youremptytestdbnamehere/wordpress_test/ wp-tests-config.php
+ sed -i s/yourusernamehere/root/ wp-tests-config.php
+ sed -i s/yourpasswordhere// wp-tests-config.php
+ sed -i 's|localhost|localhost|' wp-tests-config.php
+ install_db
+ PARTS=(${DB_HOST//\:/ })
+ local PARTS
+ local DB_HOSTNAME=localhost
+ local DB_SOCK_OR_PORT=
+ local EXTRA=
+ '[' -z localhost ']'
+ [[ '' =~ ^[0-9]+$ ]]
+ '[' -z ']'
+ '[' -z localhost ']'
+ EXTRA=' --host=localhost --protocol=tcp'
+ mysqladmin create wordpress_test --user=root --password= --host=localhost --protocol=tcp
```

**Comment by davisshaver** [comment]
So maybe it's a permissions error, and using bash just gets around it?

**Comment by anthony2727** [comment]
Check the owner and group of install-wp-tests.sh

**Comment by goldenapples** [comment]
> So maybe it's a permissions error, and using bash just gets around it?

OK, that sounds possible. I think might have done something different in configuring permissions for my shared folders. What's the line in your Vagrantfile configuring the shared folder look like?

**Comment by davisshaver** [comment]
@anthony2727 @goldenapples I'm using a clean VIP Quickstart vagrant machine. https://github.com/Automattic/vip-quickstart/blob/master/Vagrantfile

Permissions look like this:
```
-rw-rw-r-- 1 www-data www-data 3380 Jun 15 13:17 install-wp-tests.sh
```

**Comment by goldenapples** [comment]
Yeah, it looks like your permissions on the file are off somehow. It should have been set to 755, from this commit: https://github.com/fusioneng/fusion-theme/commit/6086d85d2c3f41c3271c68a2a17e7a1bc78ed2c8

Did you clone the repository inside Vagrant? Or are you using a shared folder in your host machine?

I don't have a problem telling people to run the file using `bash` - its an easy workaround, but I'd like to have dev environment setup instructions that are reproducible.

**Comment by davisshaver** [comment]
@goldenapples I cloned from local as per tech-docs: https://github.com/fusioneng/tech-docs/blob/master/wordpress-development/vip-quickstart.md

Is it better to clone from within the vagrant?

**Comment by anthony2727** [comment]
@davisshaver @goldenapples can you share the content of **"install-wp-tests.sh"**? It looks like part of a private repo.

**Comment by anthony2727** [comment]
Ok guys, I think it doesn't matter whether You clone the repo either from the shared or the guess' folder but I remember that Vagrant provides options for the synced_folder (check below).
```
config.vm.synced_folder "local_folder", "guess folder",
    owner: "vagrant",
    group: "www-data",
    mount_options: ["dmode=775,fmode=664"]
```  
This way we can ensure the right configuration for the owner, group and permission for the files and directories. 

I hope you find it useful. 
Thanks, 
@davisshaver @goldenapples @danielbachhuber

**Comment by davisshaver** [comment]
@goldenapples I still need to specify `bash` when setting up VIP installs. Maybe @than can report back after his onboarding setup.

**Comment by than** [comment]
I had no issues with bash when I setup VIP locally.

**Comment by davisshaver** [comment]
Just realized this is probably bc I use ZSH. Closing based on @than's most recent comment.

**Pull request closed without merging**
